### ISSUE TITLE
your app is not complete,

### ISSUE THREAD

**Issue by bokrma** [yugal-jain/email-sync-engine#1]
your app is not complete,
the app should have a complete sync of any email data exists on the email provider server in our local database
and it should sync the changes in the data in real life (so cron jobs are the the way to fetch the data and keep the sync)
but I only see your app syncing inbox folder which is not the case of real-life email client app that should fetch the emails from all Mailboxes

**Comment by yugal-jain** [comment]
Got it @bokrma !

I've implemented the complete sync functionality and pushed the updated code.

**Comment by yugal-jain** [comment]
@bokrma  Also updated code for delete cron job once user signed out.

**Comment by bokrma** [comment]
Unfortunately the solution still not complete, and in real-life application, this solution doesn't work, and you are only syncing inbox folder

**Comment by yugal-jain** [comment]
Thank you for your feedback and for considering my submission.

I acknowledge that the current implementation only includes synchronization for the inbox folder. Due to time constraints and my current travel schedule, I was unable to complete the synchronization for all folders.

However, I am confident in my ability to address this and any other requirements if given the opportunity to join your team. I am eager to contribute my skills and collaborate with your team to develop a comprehensive and robust solution.

Thank you for your understanding and consideration.
